export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO   = 'EDITAR_PRODUCTO';
export const BORRAR_PRODUCTO   = 'BORRAR_PRODUCTO';
export const MOSTRAR_PRODUCTOS = 'MOSTRAR_PRODUCTOS';
export const MOSTRAR_PRODUCTO = 'MOSTRAR_PRODUCTO';